name: Generate GitHub Analytics

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=HaseebBasit&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true
          path: assets/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=HaseebBasit&layout=compact&langs_count=8&theme=tokyonight&hide_border=true
          path: assets/top-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit analytics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/github-stats.svg assets/top-languages.svg

          git diff --cached --quiet || git commit -m "Update GitHub analytics"

          git push
